In [2]:
import numpy as np
lst=[1,2,3]
arr=np.array(lst)
print(arr)

[1 2 3]


In [5]:
print(type(arr))
print(type(lst))

<type 'numpy.ndarray'>
<type 'list'>


In [6]:
arr=np.array([1,2,3,4])
print(arr+arr)
print(arr*arr)
print(arr/arr)

[2 4 6 8]
[ 1  4  9 16]
[1 1 1 1]


In [10]:
lst1=[i for i in range(1,6)]
#print(lst1)
arr1=np.array(lst1)
print(np.sin(arr1))
print(np.log2(arr1))
print(np.log10(arr1))
print(np.exp(arr1))


[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         1.         1.5849625  2.         2.32192809]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [17]:
arr2=np.arange(1,6)
print(arr2)
arr3=np.linspace(1,3,3)
print(type(arr3[0]))

[1 2 3 4 5]
<type 'numpy.float64'>


In [24]:
lst3=[[1,2,3],[4,5,6],[7,8,9]]
mat1=np.array(lst3)
print(mat1)
print("dimension",mat1.ndim)
print("shape",mat1.shape)
print("size",mat1.size)
print("dtype",mat1.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
('dimension', 2)
('shape', (3, 3))
('size', 9)
('dtype', dtype('int64'))


In [31]:
print "vector",np.zeros(3)
print "matrix",5*np.ones(5)

vector [0. 0. 0.]
matrix [5. 5. 5. 5. 5.]


In [32]:
print "identity matrix",np.eye(3)

identity matrix [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [37]:
print "random matrix",np.random.randint(low=0,high=10,size=(4,3))

random matrix [[3 4 4]
 [7 0 6]
 [7 7 9]
 [9 8 0]]


In [47]:
a=np.random.randint(1,100,30)
print a.shape
b=a.reshape(2,3,5)
#print b
c=a.reshape(6,5)
print c

(30,)
[[21 41 72 76 36]
 [84 21 97 68 55]
 [79 92 14 39 45]
 [84  9 87 63 38]
 [25  2 39 29 63]
 [41 77 80 64 74]]


In [50]:
a=np.array([[1,2],[3,4]])
b=np.array([[1,1],[1,1]])
print  np.vstack((a,b))
#print np.hstack((a,b))

[[1 2]
 [3 4]
 [1 1]
 [1 1]]
